version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
    env_file:
    - dev.env
    networks:
    - postgres
 
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - pgadmin_data:/root/.pgadmin
    env_file:
    - dev.env
    networks:
    - postgres
 
networks:
  postgres:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
